### ISSUE TITLE
Feature request: seeking in files

### ISSUE THREAD

**Issue by Bodertz** [xenodium/ready-player#11]
Currently, ready-player can play a file from the beginning, but there is no obvious way to skip forward to a section the user may be looking for, or to skip back to replay a section they didn't quite catch.

For videos, this is less of a problem, as a dedicated video player will pop up which will likely support seeking.  For audio files, though, the program playing the files is not shown to the user, and the user relies on Emacs commands to control playback.  Presently, there are no commands to seek in the file, but this would be useful for both audio and video.

Perhaps [1] and [2] could be used for inspiration.

[1] https://github.com/sachac/subed
[2] https://github.com/kljohann/mpv.el

**Comment by xenodium** [comment]
Thanks for filing! It'll need some investigation. Thanks for the suggested packages!

**Comment by xenodium** [comment]
Ok, maybe it's coming... ;) Need to experiment more.

![2024-08-30-17:06:22-Emacs_optimized](https://github.com/user-attachments/assets/2a8d3756-4026-439c-ac2c-b00cc235bade)

**Comment by xenodium** [comment]
As of https://github.com/xenodium/ready-player/commit/d51ef92c62011c2826117552c6cd07efde5fcdee we have experimental seek for mpv

![2024-08-31-12:24:06-Emacs_optimized](https://github.com/user-attachments/assets/1071e124-9293-48a0-96c0-ac14b5d122a4)
