### ISSUE TITLE
Feature request: create git tags for the current numbered version and in the future for version bumps

### ISSUE THREAD

**Issue by hab25** [xenodium/ready-player#12]
This will allow users to install tagged versions from MELPA Stable.

**Comment by xenodium** [comment]
Thanks for filling!

Reading the https://github.com/melpa/melpa docs, stable seems to be discouraged by the maintainers themselves:

```
Note that the MELPA maintainers do not use MELPA Stable themselves, and do not particularly recommend its use.
```

On the surface, it seems a little counterintuitive to commit to taking on a bit of extra work for a channel that's isn't recommended by the MELPA maintainers themselves?

Would you be interested in volunteering to help manage the stable release side of things for the packages you're keen on?

**Comment by xenodium** [comment]
Ok, so I've pushed version tags for both https://github.com/xenodium/ready-player and https://github.com/xenodium/dwim-shell-command. I'll give it a shot and see how it goes. Hope that helps.

**Comment by xenodium** [comment]
> IMO some rationale for such a recommendation should be added for that sentence to be useful.

I'm OK following the maintainer's recommendations. It's their gig.

> This request is just asking for a git tag to be created alongside whenever that happens; that should be, now that you've successfully created the first tag, mainly a matter of remembering to do it again when appropriate.

Can only commit to best effort here. If the stable builds break or they require additinional, I'm afraid it'll be outside of scope of what I can volunteer/commit to.

> It does, thank you very much!

Good to hear. Closing issue.
