### ISSUE TITLE
Feature request: repeat only the currently playing file

### ISSUE THREAD

**Issue by systemfreund** [xenodium/ready-player#16]
Instead of playing the next file in the directory repeat the currently playing file instead.

(This mode is exactly what I was looking for btw, great work!)

**Comment by xenodium** [comment]
Thanks for filing a feature request.

> Instead of playing the next file in the directory repeat the currently playing file instead.

Added in https://github.com/xenodium/ready-player/commit/34328a0e5b40930d8d4fb02e8a8810e53fd49e4f.

Set `ready-player-repeat` to `'file` or use `M-x ready-player-toggle-repeat`. Give v0.13.1 a try.

> (This mode is exactly what I was looking for btw, great work!)

Thank you. Great to hear. Please consider [sponsoring](https://github.com/sponsors/xenodium) the project to make feature requests, improvements, and maintenance sustainable.

**Comment by xenodium** [comment]
Feature's in place. Gonna go ahead and close this feature request.
