### ISSUE TITLE
Global keybinding prefix

### ISSUE THREAD

**Issue by marczz** [xenodium/ready-player#19]
The global keybinding prefix is hardcoded to "C-c C-m". 

This prefix is not convenient for everybody, specially emacs evil users would like to bind it under a leader key.

Presently the only way would be to disable the global bindings and rewrite them with another binding.

It would be easy in you code to define a custom variable readyplayer-prefix and use it in your minor mode code. 

The code would also be simpler by defining a global binding keymap, it would also avoid to give a redundant copy of the same bindings for enabling and disabling the global bindings.

**Comment by xenodium** [comment]
Thanks for filing!

Much of ready-player code was initially scratching my own itch, but have since modified as the feature requests come in. 

> It would be easy in you code to define a custom variable readyplayer-prefix and use it in your minor mode code.

Sounds good. Would you be keen to send a pull request?

**Comment by xenodium** [comment]
Thanks for submitting changes to handle this.

>  specially emacs evil users would like to bind it under a leader key.

I'm guessing you're an evil user? Can you share how you set things up for evil usage? I can add those details to README.

Now I'm wondering, does ready-player-major-mode need additional changes to work with evil bindings? Sorry not an evil user here.

**Comment by marczz** [comment]
I am just beginning to use ready player, and I have still many problem with it, both when using and for configuring.
The configuration is more intricate due to the lack of autoloads in the package (you should provide them for the keymaps and interactive commands)
So presently I have in my config to commands for the same entry in my leader keymap, one before the package is loaded and a second one when it is loaded. I will delete the extra binding, once the autolaods will be set.

In any case this is a configuration that will evolve, when I will get habituated to the package.

I give my provisional version.
```
  (use-package ready-player
    :ensure t
    :defer t
    :init
    (autoload #'ready-player-mode "ready-player" nil )
    :general
    (mz/media-map
     "r" '("ready-player-mode" . (lambda nil (interactive) (ready-player-mode +1))))
    ;; evil/vim compatible bindings
    (ready-player-major-mode-map
     :states '(normal motion)
     "TAB"   #'ready-player-next-button
     "<backtab>" #'ready-player-previous-button
     "p"   #'ready-player-toggle-play-stop
     "g r"   #'ready-player-reload-buffer
     "r"     #'ready-player-toggle-repeat
     "d"     #'ready-player-view-dired-playback-buffer
     "s"     #'ready-player-toggle-shuffle
     "a"     #'ready-player-toggle-autoplay
     "o"     #'ready-player-open-externally
     "c"     #'ready-player-open-my-media-collection
     "?"     #'ready-player-show-info
     "m"     #'ready-player-mark-dired-file
     "u"     #'ready-player-unmark-dired-file
     "C-j"   #'ready-player-next
     "C-k"   #'ready-player-previous
     "g h"   #'ready-player-seek-backward
     "g j"   #'ready-player-next
     "g k"   #'ready-player-previous
     "g l"   #'ready-player-seek-forward
     )
    (ready-player-minor-mode-map
     "m" #'ready-player-view-player
     "/" #'ready-player-search
     "j" #'ready-player-next
     "k" #'ready-player-previous
     "?" #'ready-player-show-info
     "c" #'ready-player-open-my-media-collection
     "p" #'ready-player-toggle-play-stop
     "r" #'ready-player-toggle-repeat
     "s" #'ready-player-toggle-shuffle
     "a" #'ready-player-toggle-autoplay
     )
    :config
    (ready-player-mode +1)
    (general-def mz/media-map
     "r" (cons "Ready Player" ready-player-minor-mode-map))
    (setq ready-player-my-media-collection-location
          "~/Videos")
    )
```

Here `mz/media-map` is a submap of my leader keymap, which use "SPC" as leader key. It is why I cannot use it in the previous maps. I also try to comply with the rules of evil-collection.

**Comment by xenodium** [comment]
Ah, no need to jump through hoops to config. If there are autoloads missing, we can add those. Added https://github.com/xenodium/ready-player/commit/4b11f29afbd146b07203af1128cab6012bda4057. Does that resolve it, or are there others needed? I've never used evil, so I may need your contribution to make that experience better.

**Comment by karthink** [comment]
I updated ready-player after a while and noticed that it's clobbering my user-defined `C-c m` bindings in all buffers.  @xenodium will you consider binding the default global prefix somewhere outside of the `C-c <a-z>` range?

This range is [reserved for user-defined keys](https://www.gnu.org/software/emacs/manual/html_node/elisp/Key-Binding-Conventions.html) under the Emacs-lisp coding conventions, and is expected to not be bound by packages.

**Comment by karthink** [comment]
Very well,  thanks for considering it.
