### ISSUE TITLE
Play button now shown

### ISSUE THREAD

**Issue by e40** [xenodium/ready-player#5]
The play button looks like it's not installed.  Is this an unreported dependency?

![Screenshot 2024-07-05 at 2 01 40 PM](https://github.com/xenodium/ready-player/assets/89416/78dc607c-b32c-4e67-9110-a2d719686081)

Emacs is 29.3 from emacsformacosx.com, which I've always used over the `brew` version.

Ideas?

**Comment by xenodium** [comment]
Ah, the package uses SF symbols on a macOS, but looks like you may need to enable it.

'''emacs-lisp
;; Enable rendering SF symbols on macOS.
(when (memq system-type '(darwin))
  (set-fontset-font t nil "SF Pro Display" nil 'append))
'''

I should guard against that.

If that doesn't work, can you try setting to

(setq ready-player-play-icon "⏵")
(setq ready-player-open-externally-icon "➦")
(setq ready-player-stop-icon "■")

**Comment by e40** [comment]
The 1st one didn't work, but the 2nd one did.  Thanks.

**Comment by xenodium** [comment]
Good to know. Changed the defaults. Gonna close issue. Thanks!

**Comment by e40** [comment]
Thanks, @xenodium!  I "Upgraded" wit this:
```
(package-vc-install "https://github.com/xenodium/ready-player" :last-release)
```
and removed the special hack you gave me, works fine.

**Comment by xenodium** [comment]
Oh, handy. I've added `:last-release` to install notes.
