### ISSUE TITLE
Add the equivalent of `image-mode-mark-file`?

### ISSUE THREAD

**Issue by karthink** [xenodium/ready-player#8]
Hi @xenodium, this is a nifty package, thank you.

I think binding an equivalent of `image-mode-mark-file` to `m` in the ready-player buffer will be quite helpful, and maintain parity with the image-mode interface.  For reference, here's what `image-mode-mark-file` does:

```
Mark the current file in the appropriate Dired buffer(s).
Any Dired buffer that’s opened to the current file’s directory
will have the line where the image appears (if any) marked.

If no such buffer exists, it will be opened.
```

**Comment by xenodium** [comment]
> Hi @xenodium,

Hi @karthink!

> this is a nifty package, thank you.

Glad you like it :)

> I think binding an equivalent of image-mode-mark-file to m in the ready-player buffer will be quite helpful

OK! Added in 2469231ffc8fcac45d4a41d672c5b75cdab04642. Try `ready-player-(un)mark-dired-file` /  `m/u`.

**Comment by karthink** [comment]
Works great, thanks!
