### ISSUE TITLE
Feature request: Play-on-select, open in existing buffer

### ISSUE THREAD

**Issue by claytharrison** [xenodium/ready-player#9]
Ready Player is really nice - I livecode music in Emacs and I can see it being really handy for flipping through sample banks. Every other music player for emacs seems to care a lot about playlists and metadata but all I care about is launching tracks from dired.

To that end, it would be great if there were some options to 1) play media as soon as I select it from dired/whatever, 2) reuse an existing buffer it already exists, and 3) not move focus to the ready-player buffer when selecting a track from outside it. I see myself scrolling through dired playing short samples one at a time to find which ones I like and marking them for moving into a "Favorites" folder. Ideally I press `RET` to play the track and then can just quickly move down to the next and press `RET` to stop the current track and start the new one.

Of course it would be easy to use open-with to just get mpv to play the tracks outside of Emacs, but I love that ready-player just keeps everything within the Emacs instance.

**Comment by claytharrison** [comment]
> Cool! Can I watch/hear it somewhere?

Sure, we've only got one thing up on youtube so far but more should be coming quite soon if you enjoy this kind of thing:
https://www.youtube.com/watch?v=ExSPJZQvBec

> You could rebind o to something like

Ah yes that does the trick, thanks! Just need the autoplay and something to kill any currently-playing track when a new one is opened and everything should work fine.

I also started messing around with Doom's popup-rules to get media buffers to open as popups instead of full windows, since that framework also contains an option for where to keep focus. I got it to work with a `.wav` buffer once but can't reproduce it for some reason.

> Curious, what OS are you using it on?

Just Linux, Pop!_OS 22.04

**Comment by xenodium** [comment]
> more should be coming quite soon if you enjoy this kind of thing

Yeah sure!

> Just need the autoplay and something to kill any currently-playing track when a new one is opened and everything should work fine.

Ok, I think I got everything going in the latest. Take it for a spin and see if that works.

There's a new setting `ready-player-autoplay` also shown in a toggable button. Single-buffer mode is now the default (can be overriden with `ready-player-multi-buffer`).

> This one needs changes to your dired config/binding.
> 
>(defun dired-find-file-other-window-no-switch ()
 >  "In Dired, visit this file or directory in another window and keep focus."
 >  (interactive)
 >  (save-selected-window
 >    (dired-find-file-other-window)))(defun dired-find-file-other-window-no-switch ()
 >  "In Dired, visit this file or directory in another window and keep focus."
 >  (interactive)
 >  (save-selected-window
 >    (dired-find-file-other-window)))

Actually, peep dired seems to work pretty nicely for this: https://github.com/asok/peep-dired. I forgot I had it bound to `P`. `C-n` and `C-p` do what you'd expect.

![2024-07-16-13:01:40-Emacs](https://github.com/user-attachments/assets/38edeb47-e9a9-4fc6-aeef-18d8e6ac90d5)

**Comment by xenodium** [comment]
I discovered `dired-preview` today. May be a better alternative to `peep-dired` https://github.com/protesilaos/dired-preview

You can see it in use at https://indieweb.social/@xenodium/112796504897011874

**Comment by xenodium** [comment]
Closing. If not mistaken, all requests here are now implemented in the latest. Please reopen if otherwise.

**Comment by claytharrison** [comment]
Just finally got around to testing this out yesterday, it all works great. Thanks again!

**Comment by xenodium** [comment]
Great to hear!

**Comment by claytharrison** [comment]
OK I may have lied a bit back then because I didn't have time to play around with it and wanted to just say thanks. Everything does work nicely as we talked about here, but the problem for this usecase is that ready-player automatically plays the next track when the previous finishes. Of course the intended and desired behavior most of the rest of the time but not so great when you just want to quickly hear a single, very short file. It would be great if there were an option to turn off auto-next-track

**Comment by xenodium** [comment]
Toggle `ready-player-toggle-repeat` a couple of times until it says `Repeat: OFF`

**Comment by claytharrison** [comment]
Ah I missed that - thanks!

**Comment by xenodium** [comment]
> ! I'm used to 'repeat' toggling between "repeat album/whatever when done", "repeat song when done", or "play album/whatever until the end of the album then stop", so didn't think to look there

Ah yes. Those are mostly there.

> repeat song when done"

Repeat: current file

> "repeat album/whatever when done"

Repeat: playlist

> "play album/whatever until the end of the album then stop"

Repeat: playlist

Playlist can mean different things depending on what you opened. If you just opened a file in a directory, that directory becomes the playlist.

If you're finding the package useful, consider [supporting](https://github.com/sponsors/xenodium) to enable sustainalbe development and support.
